# remove it if you don't want to force ssl
#FORCE_SSL: 'false'

SECRET_KEY_BASE: "rake secret"
DEVISE_SECRET_KEY: "rake secret"

# if you want to allow the users to login via facebook fill these variables
FACEBOOK_APP_ID: ""
FACEBOOK_APP_SECRET: ""

# if you want to allow the users to login via google fill these variables
GOOGLE_APP_ID: ""
GOOGLE_APP_SECRET: ""

# if you want to allow the users to login via twitter fill these variables
TWITTER_APP_ID: ""
TWITTER_APP_SECRET: ""

# if you want to allow the users to login via meetup fill these variables
MEETUP_APP_ID: ""
MEETUP_APP_SECRET: ""

# if you want to allow the users to login via linkedin fill these variables
LINKEDIN_APP_ID: ""
LINKEDIN_APP_SECRET: ""

# if you want to allow the users to login via Parma fill these variables
PARMA_APP_ID: ""
PARMA_APP_SECRET: ""

# if you want to allow the users to login via Tecnologie Democratiche fill these variables
# send an email to alessandro.rodi@airesis.it to ask for credentials
TECNOLOGIEDEMOCRATICHE_APP_ID: ''
TECNOLOGIEDEMOCRATICHE_APP_SECRET: ''
TECNOLOGIEDEMOCRATICHE_APP_URL: "https://tecnologiedemocratiche.herokuapp.com/"

# google maps api key. obtain one from google developers console
# registering a new application and generating a new browser key
MAPS_API_KEY: "NvVyXBNlG8dEkQG8LMa5eFuj"

# if you are using google analytics put in here the ID
GOOGLE_ANALYTICS_ID: "YOUR GOOGLE ANALYTICS ID"

# do you want to protect registration via captcha? fill these variables!
RECAPTCHA_PUBLIC: ""
RECAPTCHA_PRIVATE: ""

# go to geonames.org and obtain a username to put in here
GEOSPATIAL_NAME: "zmdroid"

#####################
#email service
#####################
EMAIL_ADDRESS: "393012998@qq.com"
EMAIL_USERNAME: "393012998"
EMAIL_PASSWORD: "zm198933#@!"

MAILER_DEFAULT_HOST: "smtp.qq.com"

# set your email address to override email receiver in development and test
OVERRIDE_MAIL_RECIPIENT: "393012998@qq.com"

#####################
#newsletter parameters
#####################
NEWSLETTER_FROM_ADDRESS: ""
NEWSLETTER_TWITTER_URL: ""
NEWSLETTER_FACEBOOK_URL: ""
NEWSLETTER_GOOGLEPLUS_URL: ""
NEWSLETTER_PREFERENCES_URL: ""
NEWSLETTER_HOME_URL: ""

#####################
# feedbacks (optional)
# set these values to send and receive feedbacks from users
#####################
FEEDBACK_SENDER: "Feedback <393012998@qq.com>"
FEEDBACK_RECEIVER: "393012998@qq.com"

#####################
# email settings (required)
# email addresses for all email services
#####################
DEFAULT_FROM: "393012998@qq.com"
NOREPLY_EMAIL: "No Reply <393012998@qq.com>"

# when we send emails the default protocol to use for urls.
# airesis tries not to use the rails default ActionMailer Default Host
# because it depends on which host the user registered.
# You still have the MAILER_DEFAULT_HOST for emails which are not directed to registered users.
# for other users the domain on which they registered counts and this is the protocol used.
# you can specify http or https. if not specified the default is https.
DEFAULT_EMAIL_PROTOCOL: 'http'

#####################
#redmine integration (optional)
#####################
BUGTRACKING_URL: ""
BUGTRACKING_USERNAME: ""
BUGTRACKING_PASSWORD: ""

#####################
#application parameters
#####################
APP_SHORT_NAME: "我的地盘"
APP_LONG_NAME: "我的地盘 - 我的宣言"

# default reference email address for the website. is used in the app to tell the user which email address he
# has to contact for information. it is also shown in the footer of the emails as main contact address.
APP_EMAIL_ADDRESS: "393012998@qq.com"

# default administrator credentials
ADMIN_EMAIL: "972620408@qq.com"
ADMIN_PASSWORD: "password"

# sitemap host and email assets url (for images)
SITE: "http://114.215.237.28:3000"

# where is listening your redis installation? development
#REDIS_URL: "redis://127.0.0.1:6379/12"
#production
REDIS_URL: "redis://114.215.237.28:6379/12"

# remove these variables if you are not using amazon s3
AWS_HOST: "s3-eu-west-1.amazonaws.com"
AWS_BUCKET: ""
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""

# assets on a cdn. remove it if you are not using a cdn
ASSETS_HOST: ""

# remove this variable if you are not using cloudfront. set it to cloudfront alias if you want to you it
AWS_ALIAS: "static.yourwebsite.com"

# Newrelic configurations
NEW_RELIC_LICENSE_KEY: '657bf227d6467a26696032403b7e4194621969ff'
NEW_RELIC_APP_NAME: 'SheQu'

#####################
#crowdin integration (optional)
#####################
CROWDIN_API: ""
CROWDIN_PROJECT_ID: ""
CROWDIN_ACCOUNT_KEY: ""

#####################
#capistrano settings (optional)
#####################
CAP_STAGING_USER: ""
CAP_STAGING_SERVER: ""


##############
#sentry settings. remove these keys to not use it (leaving them empty will throw an error)
#https://d9cd0288b9184dbf9a7eaf4a327cd202:f6470751e352475ca470d7b07f103cb6@app.getsentry.com/59525
#############
SENTRY_PUBLIC_KEY: "d9cd0288b9184dbf9a7eaf4a327cd202"
SENTRY_PRIVATE_KEY: "f6470751e352475ca470d7b07f103cb6"
SENTRY_PORT: "59525"

#############
# environment constants (leave default values for default behaviour, change them to change platform behaviour)
# the values are the ones used on airesis official installation
#############

#percentage of active users on the platform. this number is used to calculate quorums in the open space only
#the calculation is quorum.percentage * (users * ACTIVE_USER_PERCENTAGE)
#if you have 100 registered users and a 50% quorum the number of valutations and votes is 50 (0.5 * (100 * 1)).
#if you change this value to 30, then the number of valutations and votes will be 15 (0.5 * (100 * 0.3)).
#if you change this value to 10, then the number of valutations and votes will be 5 (0.5 * (100 * 0.1)).
#this is useful to provide accessible quorums in the open space. maybe one day will not be necessary
#allow integers, required
ACTIVE_USERS_PERCENTAGE: "100"

#this is the maximum length for a contribute or a comment in proposals or blog
#allow integers, required
CONTRIBUTE_MAX_LENGTH: "2200"

#minimum amount of marks for a contribute to be eligible for deletion
CONTRIBUTE_MARKS: "3"

#minimum amount of time between the end of debate and the beginning of vote. please do not set it below few minutes.
#must be specified in minutes
DEBATE_VOTE_DIFFERENCE: "10"

#max number of comments per page
COMMENTS_PER_PAGE: "5"
#max number of proposals per page
PROPOSALS_PER_PAGE: "10"

#max number of topics per page
TOPICS_PER_PAGE: "10"

#contributes and comments are limited for each user?
LIMIT_COMMENTS: "false"

#if contributes and comments are limited this is the minimum amount of time between two subsequent comments from the same user
#must be specified in seconds
COMMENTS_TIME_LIMIT: "30"

#proposals are limited for each user?
LIMIT_PROPOSALS: "false"

#if proposals are limited this is the minimum amount of time between two subsequent proposals from the same user
#must be defined in seconds
PROPOSALS_TIME_LIMIT: "60"

# the number of minutes within you can destroy a proposal or edit some of the attributes
# after that time (in minutes!) the users will not be able to destroy the proposal or edit some fields
# if this variable is not set the default is 10 minutes
EDIT_PROPOSAL_TIME_LIMIT: '10'

#groups creation is limited?
LIMIT_GROUPS: "true"

#if groups creation is limited this is the minimum amount of time between two subsequent creations from the same user
#must be specified in hours
GROUPS_TIME_LIMIT: "24"

#if you are using tokens for voting yoy may need to set a drift for token creation.
#must be specified in seconds
ROTP_DRIFT: "20"

#default options when for groups when created.
#the owner of the group can always change them after he created the group but the 90% of users will
#use default values so it makes the difference

#can users of a group change the settings of a proposal when it's created?
#default is false: it means that the proposals settings will be selected by the group administrator
#allow true,TRUE,false,FALSE, required
DEFAULT_CHANGE_ADVANCED_OPTIONS: "false"

#the discussion is anonimous?
#default is true: it means that the proposal's discussion will be anonimous
#allow true,TRUE,false,FALSE, required
DEFAULT_ANONIMA: "true"

#actions enabled by default for users when they join a group. Look at GroupAction model to see available values.
#expert variable, don't touch it if you don't know what are you going to do
DEFAULT_GROUP_ACTIONS: "1, 2, 6, 7, 8, 9, 11, 12"

#actions enabled by default for users when they join a group area. Look at GroupAction model to see available values
#expert variable, don't touch it if you don't know what are you going to do
DEFAULT_AREA_ACTIONS: "6, 7, 8, 11, 12"

#after this number of days, if the author has not chose a voting date, the users which have the right to choose a vote day, can do it
OTHERS_CHOOSE_VOTE_DATE_DAYS: "5"

### PAYPAL CONFIGURATION ###

PAYPAL_MERCHANT: "YOURMERCHANTID"
#test
#PAYPAL_URL: "https://www.sandbox.paypal.com/cgi-bin/webscr"
#production:
#PAYPAL_URL: "https://www.paypal.com/cgi-bin/webscr"

# path to wkhtmltopdf exacutable
# if this variable is not set then the value of `which wkhtmltopdf` is taken.
WKHTMLTOPDF_PATH: '/usr/bin/wkhtmltopdf'
