development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://shequpubserver.herokuapp.com/faye"
  secret_token: "9d7e3b08d7530b87aa4d7bc710587cdf5329dbe692cb0cf0c37d2fa6b729c29d6c47f8b6012ce5f4716ddb814ce9be4cd857bae4b3629d881d374d7063b7f4ae"
test:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
